import type { Procedure } from '@/types'

export const PROCEDURES: Procedure[] = [
  {
    id: 'foto-terapia-facial',
    slug: 'foto-terapia-facial',
    name: 'Foto Terapia Facial',
    shortName: 'LED Facial',
    audience: 'misto',
    description:
      'Fotobiomodulação com painéis LED de comprimentos de onda específicos para renovação celular, síntese de colágeno e uniformização da pele.',
    color_primary: '#1a6a8a',
    color_accent: '#4FC3F7',
    icon: '✦',
    slides: [
      {
        id: 'ftf-1',
        order: 1,
        duration: 15,
        type: 'gancho',
        title: 'A luz que transforma sua pele',
        subtitle: 'Sem agulhas. Sem dor. Sem downtime.',
      },
      {
        id: 'ftf-2',
        order: 2,
        duration: 15,
        type: 'definicao',
        title: 'Foto Terapia Facial',
        subtitle: 'Tecnologia LED para renovação celular',
        body: ['Estimula colágeno', 'Auxilia na uniformização do tom', 'Sem procedimento invasivo'],
      },
      {
        id: 'ftf-3',
        order: 3,
        duration: 15,
        type: 'procedimentos',
        title: 'Como funciona',
        body: [
          '✦ Luz vermelha — estimula colágeno',
          '✦ Luz infravermelha — regeneração profunda',
          '✦ Luz azul — auxílio no controle da oleosidade',
          '✦ Sessão de 20–30 min, relaxante',
        ],
      },
      {
        id: 'ftf-4',
        order: 4,
        duration: 15,
        type: 'beneficios',
        title: 'Resultados visíveis',
        subtitle: 'Desde a primeira sessão',
        body: ['Protocolo personalizado', 'Sem contraindicações para a maioria', 'Retorno imediato às atividades'],
      },
      {
        id: 'ftf-5',
        order: 5,
        duration: 15,
        type: 'cta',
        title: 'Você já está no lugar certo',
        subtitle: 'Pergunte sobre Foto Terapia na sua consulta de hoje',
        cta: '[CONTATO] | [NOME DA CLÍNICA]',
      },
    ],
  },
  {
    id: 'botox',
    slug: 'botox',
    name: 'Toxina Botulínica',
    shortName: 'Botox',
    audience: 'misto',
    description:
      'Aplicação de toxina botulínica para suavizar linhas de expressão com precisão clínica, resultado natural e duração em média de 4 a 6 meses.',
    color_primary: '#2d6a4f',
    color_accent: '#74c69d',
    icon: '◆',
    slides: [
      {
        id: 'btx-1',
        order: 1,
        duration: 15,
        type: 'gancho',
        title: 'Sua expressão,\nsó que mais suave',
        subtitle: 'Sem alterar quem você é.',
      },
      {
        id: 'btx-2',
        order: 2,
        duration: 15,
        type: 'definicao',
        title: 'Toxina Botulínica',
        subtitle: 'Relaxamento preciso dos músculos de expressão',
        body: ['Procedimento de 15–30 min', 'Resultado em 7–14 dias', 'Dura, em média, 4 a 6 meses'],
      },
      {
        id: 'btx-3',
        order: 3,
        duration: 15,
        type: 'procedimentos',
        title: 'Áreas tratadas',
        body: [
          '◆ Testa (linhas horizontais)',
          '◆ Glabela (entre as sobrancelhas)',
          '◆ Pés de galinha',
          '◆ Pescoço e platisma',
        ],
      },
      {
        id: 'btx-4',
        order: 4,
        duration: 15,
        type: 'beneficios',
        title: 'Resultado natural',
        subtitle: 'Sem cirurgia · Retorno imediato',
        body: ['Realizado por médico especialista', 'Expressões naturais preservadas', 'Manutenção programada'],
      },
      {
        id: 'btx-5',
        order: 5,
        duration: 15,
        type: 'cta',
        title: 'Você já está no lugar certo',
        subtitle: 'Pergunte sobre Toxina Botulínica na sua consulta de hoje',
        cta: '[CONTATO] | [NOME DA CLÍNICA]',
      },
    ],
  },
  {
    id: 'harmonizacao-intima-feminina',
    slug: 'harmonizacao-intima-feminina',
    name: 'Harmonização Íntima Feminina',
    shortName: 'H. Íntima Fem.',
    audience: 'feminino',
    description:
      'Procedimentos estéticos não cirúrgicos para conforto, bem-estar e autoestima: preenchimento labial íntimo, laser vaginal, radiofrequência e clareamento.',
    color_primary: '#8b4b6b',
    color_accent: '#f2d0c0',
    icon: '✿',
    slides: [
      {
        id: 'hif-1',
        order: 1,
        duration: 15,
        type: 'gancho',
        title: 'Seu corpo merece\no mesmo cuidado',
        subtitle: 'que você dedica ao seu rosto.',
      },
      {
        id: 'hif-2',
        order: 2,
        duration: 15,
        type: 'definicao',
        title: 'Harmonização Íntima Feminina',
        subtitle: 'Procedimentos não cirúrgicos para conforto e bem-estar',
        body: ['Sem internação', 'Retorno imediato', 'Médico especialista'],
      },
      {
        id: 'hif-3',
        order: 3,
        duration: 15,
        type: 'procedimentos',
        title: 'Procedimentos disponíveis',
        body: [
          '✿ Preenchimento labial íntimo',
          '✿ Clareamento da região vulvar',
          '✿ Radiofrequência e laser vaginal',
          '✿ Remodelagem com bioestimuladores',
        ],
      },
      {
        id: 'hif-4',
        order: 4,
        duration: 15,
        type: 'beneficios',
        title: 'Desconforto, flacidez ou ressecamento têm solução',
        subtitle: 'Resultados desde a 1ª sessão · Sem internação',
      },
      {
        id: 'hif-5',
        order: 5,
        duration: 15,
        type: 'cta',
        title: 'Você já está no lugar certo',
        subtitle: 'Pergunte sobre Harmonização Íntima na sua consulta de hoje',
        cta: '[CONTATO] | [NOME DA CLÍNICA]',
      },
    ],
  },
  {
    id: 'harmonizacao-intima-masculina',
    slug: 'harmonizacao-intima-masculina',
    name: 'Harmonização Íntima Masculina',
    shortName: 'H. Íntima Masc.',
    audience: 'masculino',
    description:
      'Procedimentos minimamente invasivos para autoestima e conforto masculino: bioplastia peniana, scrotox, clareamento íntimo e bioestimuladores.',
    color_primary: '#1B4F72',
    color_accent: '#4FC3F7',
    icon: '◈',
    slides: [
      {
        id: 'him-1',
        order: 1,
        duration: 15,
        type: 'gancho',
        title: 'Homens também merecem se sentir bem',
        subtitle: 'em todos os aspectos.',
      },
      {
        id: 'him-2',
        order: 2,
        duration: 15,
        type: 'definicao',
        title: 'Harmonização Íntima Masculina',
        subtitle: 'Procedimentos estéticos para autoestima e conforto',
        body: ['Resultado imediato', 'Retorno em 24–48h', 'Sigilo total'],
      },
      {
        id: 'him-3',
        order: 3,
        duration: 15,
        type: 'procedimentos',
        title: 'Procedimentos disponíveis',
        body: [
          '◈ Bioplastia peniana (volume e forma)',
          '◈ Scrotox (conforto e estética)',
          '◈ Clareamento da região íntima',
          '◈ Bioestimuladores de colágeno',
        ],
      },
      {
        id: 'him-4',
        order: 4,
        duration: 15,
        type: 'beneficios',
        title: 'Resultado imediato, sem cirurgia',
        subtitle: 'Sigilo total · Retorno em 24–48h · Médico especialista',
      },
      {
        id: 'him-5',
        order: 5,
        duration: 15,
        type: 'cta',
        title: 'Avaliação confidencial\nsem julgamentos',
        subtitle: 'Agende sua consulta',
        cta: '[CONTATO] | [NOME DA CLÍNICA]',
      },
    ],
  },
]

export const DEFAULT_CLINIC = {
  id: 'default',
  name: '[NOME DA CLÍNICA]',
  contact: '[CONTATO]',
  tagline: 'Estética avançada com cuidado personalizado',
  color_primary: '#1B4F72',
  color_accent: '#D4AF37',
}
